package com.cris.loco_master;

import com.orchestranetworks.schema.*;

/**
 * Generated by TIBCO EBX(R) 1214:0002, at 2023/03/22 23:14:01 [CET].
 * WARNING: Any manual changes to this class may be overwritten by generation process.
 * DO NOT MODIFY THIS CLASS.
 * 
 * This interface defines constants related to schema [Module: loco_master, path: /WEB-INF/ebx/schemas/loco_master.xsd].
 * 
 * Root paths in this interface: 
 * 	'/root'   relativeToRoot: false
 * 
 */
public interface Paths
{
	// ===============================================
	// Constants for nodes under '/root'.
	// Statistics:
	//		154 path constants.
	//		108 leaf nodes.
	public static final Path _Root = Path.parse("/root");

	// Table type path
	public final class _Root_Locomotive
	{
		private static final Path _Root_Locomotive = _Root.add("Locomotive");
		public static Path getPathInSchema()
		{
			return _Root_Locomotive;
		}
		public static final Path _Root_Locomotive_Loco_Number = Path.parse("./Loco_Number");
		public static final Path _Root_Locomotive_Loco_Type = Path.parse("./Loco_Type");
		public static final Path _Root_Locomotive_Loco_Commissioning_Date = Path.parse("./Loco_Commissioning_Date");
		public static final Path _Root_Locomotive_Loco_Manufacturer = Path.parse("./Loco_Manufacturer");
		public static final Path _Root_Locomotive_Loco_Control_Type = Path.parse("./Loco_Control_Type");
		public static final Path _Root_Locomotive_Loco_Permanent_Domain = Path.parse("./Loco_Permanent_Domain");
		public static final Path _Root_Locomotive_Loco_Service_Type = Path.parse("./Loco_Service_Type");
		public static final Path _Root_Locomotive_Loco_Traction_Motor_Type = Path.parse("./Loco_Traction_Motor_Type");
		public static final Path _Root_Locomotive_Loco_Owning_Zone = Path.parse("./Loco_Owning_Zone");
		public static final Path _Root_Locomotive_Loco_Owning_Division = Path.parse("./Loco_Owning_Division");
		public static final Path _Root_Locomotive_Loco_Owning_Shed = Path.parse("./Loco_Owning_Shed");
		public static final Path _Root_Locomotive_Loco_Boogie_Type = Path.parse("./Loco_Boogie_Type");
		public static final Path _Root_Locomotive_Loco_Brake_Type = Path.parse("./Loco_Brake_Type");
		public static final Path _Root_Locomotive_Loco_Rtis_Flag = Path.parse("./Loco_Rtis_Flag");
		public static final Path _Root_Locomotive_Loco_Remmlot_Flag = Path.parse("./Loco_Remmlot_Flag");
		public static final Path _Root_Locomotive_Loco_Lease_Type = Path.parse("./Loco_Lease_Type");
		public static final Path _Root_Locomotive_Loco_Manufacturing_Date = Path.parse("./Loco_Manufacturing_Date");
		public static final Path _Root_Locomotive_Loco_Receiving_Date = Path.parse("./Loco_Receiving_Date");
		public static final Path _Root_Locomotive_Loco_Entry_Date = Path.parse("./Loco_Entry_Date");
		public static final Path _Root_Locomotive_Loco_Status = Path.parse("./Loco_Status");
		public static final Path _Root_Locomotive_Loco_Hotel_Load = Path.parse("./Loco_Hotel_Load");
		public static final Path _Root_Locomotive_Loco_Cab1_AC = Path.parse("./Loco_Cab1_AC");
		public static final Path _Root_Locomotive_Loco_Cab2_AC = Path.parse("./Loco_Cab2_AC");
		public static final Path _Root_Locomotive_Loco_Auxilary = Path.parse("./Loco_Auxilary");
		public static final Path _Root_Locomotive_Loco_Brake_Sub_Type = Path.parse("./Loco_Brake_Sub_Type");
		public static final Path _Root_Locomotive_Loco_Gauge_Type = Path.parse("./Loco_Gauge_Type");
		public static final Path _Root_Locomotive_Loco_Axle_Load = Path.parse("./Loco_Axle_Load");
		public static final Path _Root_Locomotive_Loco_Hauling_Power = Path.parse("./Loco_Hauling_Power");
		public static final Path _Root_Locomotive_Loco_Traction_Code = Path.parse("./Loco_Traction_Code");
		public static final Path _Root_Locomotive_Loco_Condemn_Proposal_Type = Path.parse("./Loco_Condemn_Proposal_Type");
		public static final Path _Root_Locomotive_Loco_Condemn_Date = Path.parse("./Loco_Condemn_Date");
		public static final Path _Root_Locomotive_Loco_POH_Date = Path.parse("./Loco_POH_Date");
		public static final Path _Root_Locomotive_Loco_HRP_Flag = Path.parse("./Loco_HRP_Flag");
		public static final Path _Root_Locomotive_Loco_Hog_Flag = Path.parse("./Loco_Hog_Flag");
		public static final Path _Root_Locomotive_Loco_Kavach_Flag = Path.parse("./Loco_Kavach_Flag");
		public static final Path _Root_Locomotive_Loco_Power_Type = Path.parse("./Loco_Power_Type");
		public static final Path _Root_Locomotive_Loco_CVVRS_Type = Path.parse("./Loco_CVVRS_Type");
		public static final Path _Root_Locomotive_Loco_VCD_Flag = Path.parse("./Loco_VCD_Flag");
		public static final Path _Root_Locomotive_Loco_Pvt_Owner_Flag = Path.parse("./Loco_Pvt_Owner_Flag");
		public static final Path _Root_Locomotive_Loco_Pvt_Party_Code = Path.parse("./Loco_Pvt_Party_Code");
		public static final Path _Root_Locomotive_Allotment_Letter = Path.parse("./Allotment_Letter");
		public static final Path _Root_Locomotive_Allotment_Letter_Allotment_Letter_Number = Path.parse("./Allotment_Letter/Allotment_Letter_Number");
		public static final Path _Root_Locomotive_Allotment_Letter_Allotment_Letter_Date = Path.parse("./Allotment_Letter/Allotment_Letter_Date");
		public static final Path _Root_Locomotive_Allotment_Letter_Allotment_Letter = Path.parse("./Allotment_Letter/Allotment_Letter");
		public static final Path _Root_Locomotive_Allotment_Letter_Allotment_Letter_Attachment = Path.parse("./Allotment_Letter/Allotment_Letter/attachment");
		public static final Path _Root_Locomotive_Reference_Documents = Path.parse("./Reference_Documents");
		public static final Path _Root_Locomotive_Reference_Documents_Reference_Document_Number = Path.parse("./Reference_Documents/Reference_Document_Number");
		public static final Path _Root_Locomotive_Reference_Documents_Reference_Document_Date = Path.parse("./Reference_Documents/Reference_Document_Date");
		public static final Path _Root_Locomotive_Reference_Documents_Reference_Document = Path.parse("./Reference_Documents/Reference_Document");
		public static final Path _Root_Locomotive_Reference_Documents_Reference_Document_Attachment = Path.parse("./Reference_Documents/Reference_Document/attachment");
		public static final Path _Root_Locomotive_Audit_Info = Path.parse("./Audit_Info");
		public static final Path _Root_Locomotive_Audit_Info_Source_Record_Id = Path.parse("./Audit_Info/Source_Record_Id");
		public static final Path _Root_Locomotive_Audit_Info_Source_System_Name = Path.parse("./Audit_Info/Source_System_Name");
		public static final Path _Root_Locomotive_Audit_Info_Source_Event_Type = Path.parse("./Audit_Info/Source_Event_Type");
		public static final Path _Root_Locomotive_Audit_Info_Created_By_User = Path.parse("./Audit_Info/Created_By_User");
		public static final Path _Root_Locomotive_Audit_Info_Logged_In_User = Path.parse("./Audit_Info/Logged_In_User");
	} 

	// Table type path
	public final class _Root_Loco_Type
	{
		private static final Path _Root_Loco_Type = _Root.add("Loco_Type");
		public static Path getPathInSchema()
		{
			return _Root_Loco_Type;
		}
		public static final Path _Root_Loco_Type_MDM_Loco_Type_ID = Path.parse("./MDM_Loco_Type_ID");
		public static final Path _Root_Loco_Type_Loco_Type = Path.parse("./Loco_Type");
		public static final Path _Root_Loco_Type_Loco_Traction = Path.parse("./Loco_Traction");
		public static final Path _Root_Loco_Type_Loco_Description = Path.parse("./Loco_Description");
		public static final Path _Root_Loco_Type_Loco_Length = Path.parse("./Loco_Length");
		public static final Path _Root_Loco_Type_Loco_Hauling_Power = Path.parse("./Loco_Hauling_Power");
		public static final Path _Root_Loco_Type_Loco_Axle_Load = Path.parse("./Loco_Axle_Load");
		public static final Path _Root_Loco_Type_Loco_Axle_Unit = Path.parse("./Loco_Axle_Unit");
		public static final Path _Root_Loco_Type_Loco_Gauge_Code = Path.parse("./Loco_Gauge_Code");
	} 

	// Table type path
	public final class _Root_Loco_Sources
	{
		private static final Path _Root_Loco_Sources = _Root.add("Loco_Sources");
		public static Path getPathInSchema()
		{
			return _Root_Loco_Sources;
		}
		public static final Path _Root_Loco_Sources_MDM_Id = Path.parse("./MDM_Id");
		public static final Path _Root_Loco_Sources_Loco_Number = Path.parse("./Loco_Number");
		public static final Path _Root_Loco_Sources_Source = Path.parse("./Source");
		public static final Path _Root_Loco_Sources_Loco_Type = Path.parse("./Loco_Type");
		public static final Path _Root_Loco_Sources_Loco_Commissioning_Date = Path.parse("./Loco_Commissioning_Date");
		public static final Path _Root_Loco_Sources_Loco_Manufacturer = Path.parse("./Loco_Manufacturer");
		public static final Path _Root_Loco_Sources_Loco_Control_Type = Path.parse("./Loco_Control_Type");
		public static final Path _Root_Loco_Sources_Loco_Permanent_Domain = Path.parse("./Loco_Permanent_Domain");
		public static final Path _Root_Loco_Sources_Loco_Service_Type = Path.parse("./Loco_Service_Type");
		public static final Path _Root_Loco_Sources_Loco_Traction_Motor_Type = Path.parse("./Loco_Traction_Motor_Type");
		public static final Path _Root_Loco_Sources_Loco_Owning_Zone = Path.parse("./Loco_Owning_Zone");
		public static final Path _Root_Loco_Sources_Loco_Owning_Division = Path.parse("./Loco_Owning_Division");
		public static final Path _Root_Loco_Sources_Loco_Owning_Shed = Path.parse("./Loco_Owning_Shed");
		public static final Path _Root_Loco_Sources_Loco_Boogie_Type = Path.parse("./Loco_Boogie_Type");
		public static final Path _Root_Loco_Sources_Loco_Brake_Type = Path.parse("./Loco_Brake_Type");
		public static final Path _Root_Loco_Sources_Loco_Rtis_Flag = Path.parse("./Loco_Rtis_Flag");
		public static final Path _Root_Loco_Sources_Loco_Remmlot_Flag = Path.parse("./Loco_Remmlot_Flag");
		public static final Path _Root_Loco_Sources_Loco_Lease_Type = Path.parse("./Loco_Lease_Type");
		public static final Path _Root_Loco_Sources_Loco_Manufacturing_Date = Path.parse("./Loco_Manufacturing_Date");
		public static final Path _Root_Loco_Sources_Loco_Receiving_Date = Path.parse("./Loco_Receiving_Date");
		public static final Path _Root_Loco_Sources_Loco_Entry_Date = Path.parse("./Loco_Entry_Date");
		public static final Path _Root_Loco_Sources_Loco_Status = Path.parse("./Loco_Status");
		public static final Path _Root_Loco_Sources_Loco_Hotel_Load = Path.parse("./Loco_Hotel_Load");
		public static final Path _Root_Loco_Sources_Loco_Cab1_AC = Path.parse("./Loco_Cab1_AC");
		public static final Path _Root_Loco_Sources_Loco_Cab2_AC = Path.parse("./Loco_Cab2_AC");
		public static final Path _Root_Loco_Sources_Loco_Auxilary = Path.parse("./Loco_Auxilary");
		public static final Path _Root_Loco_Sources_Loco_Brake_Sub_Type = Path.parse("./Loco_Brake_Sub_Type");
		public static final Path _Root_Loco_Sources_Loco_Gauge_Type = Path.parse("./Loco_Gauge_Type");
		public static final Path _Root_Loco_Sources_Loco_Axle_Load = Path.parse("./Loco_Axle_Load");
		public static final Path _Root_Loco_Sources_Loco_Hauling_Power = Path.parse("./Loco_Hauling_Power");
		public static final Path _Root_Loco_Sources_Loco_Traction_Code = Path.parse("./Loco_Traction_Code");
		public static final Path _Root_Loco_Sources_Loco_Condemn_Proposal_Type = Path.parse("./Loco_Condemn_Proposal_Type");
		public static final Path _Root_Loco_Sources_Loco_Condemn_Date = Path.parse("./Loco_Condemn_Date");
		public static final Path _Root_Loco_Sources_Loco_POH_Date = Path.parse("./Loco_POH_Date");
		public static final Path _Root_Loco_Sources_Loco_HRP_Flag = Path.parse("./Loco_HRP_Flag");
		public static final Path _Root_Loco_Sources_Loco_Hog_Flag = Path.parse("./Loco_Hog_Flag");
		public static final Path _Root_Loco_Sources_Loco_Kavach_Flag = Path.parse("./Loco_Kavach_Flag");
		public static final Path _Root_Loco_Sources_Loco_Power_Type = Path.parse("./Loco_Power_Type");
		public static final Path _Root_Loco_Sources_Loco_CVVRS_Type = Path.parse("./Loco_CVVRS_Type");
		public static final Path _Root_Loco_Sources_Loco_VCD_Flag = Path.parse("./Loco_VCD_Flag");
		public static final Path _Root_Loco_Sources_Loco_Pvt_Owner_Flag = Path.parse("./Loco_Pvt_Owner_Flag");
		public static final Path _Root_Loco_Sources_Loco_Pvt_Party_Code = Path.parse("./Loco_Pvt_Party_Code");
	} 

	// Table type path
	public final class _Root_Loco_Sources_Second
	{
		private static final Path _Root_Loco_Sources_Second = _Root.add("Loco_Sources_Second");
		public static Path getPathInSchema()
		{
			return _Root_Loco_Sources_Second;
		}
		public static final Path _Root_Loco_Sources_Second_MDM_ID = Path.parse("./MDM_ID");
		public static final Path _Root_Loco_Sources_Second_Loco_Number = Path.parse("./Loco_Number");
		public static final Path _Root_Loco_Sources_Second_Overall_DQ_Score = Path.parse("./Overall_DQ_Score");
		public static final Path _Root_Loco_Sources_Second_Loco_Sources = Path.parse("./Loco_Sources");
		public static final Path _Root_Loco_Sources_Second_Loco_Type = Path.parse("./Loco_Type");
		public static final Path _Root_Loco_Sources_Second_DQ_Score = Path.parse("./DQ_Score");
	} 
	// ===============================================

}
